Feature/login update
gisat-panther/ptr-state pull request #88
Opened 2021-06-30 10:57 UTC by vdubr

- mirgate to new login/logout API
- add support for sso login
- Ensure user on mount User/AppContainer component

2021-07-12 10:00 UTC, vlach1989 requested changes

2021-07-12 11:32 UTC, vdubr commented on src/state/App/selectors.js
> +			'/backend',
Fixed here: 58f80d53a44da361b6b229583aab3dd4cbd1fd71

2021-07-12 11:33 UTC, vdubr commented on src/state/App/selectors.js
> +			'/backend',
And yes, it should be hardcoded "backend".

2021-07-12 11:37 UTC, vlach1989 approved these changes

2021-11-11 12:14 UTC, vlach1989 commented
Still relevant PR?

2026-03-17 10:57 UTC, closed without merging